---
abstract: 'Locate per-dist and per-module shared files'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
  perl: '5.006'
  vars: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-ShareDir2
provides:
  File::ShareDir2:
    file: lib/File/ShareDir2.pm
    version: '0.001000'
  File::ShareDir2::Resolver:
    file: lib/File/ShareDir2/Resolver.pm
    version: '0.001000'
  File::ShareDir2::Resolver::Perl:
    file: lib/File/ShareDir2/Resolver/Perl.pm
    version: '0.001000'
  File::ShareDir::Resolver::Perl::Legacy:
    file: lib/File/ShareDir2/Resolver/Perl/Legacy.pm
    version: '0.001000'
requires:
  Carp: '0'
  Class::Inspector: '0'
  Exporter: '0'
  File::Spec: '0'
  constant: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentfredric/File-ShareDir2/issues
  homepage: https://github.com/kentfredric/File-ShareDir2
  repository: https://github.com/kentfredric/File-ShareDir2.git
version: '0.001000'
